### ISSUE TITLE
Allow configuration of start position by URL.

### ISSUE THREAD

**Issue by diarmidmackenzie** [diarmidmackenzie/tetrisland#20]
Some users would like to be able to have the game start directly at a particular game.  Encoding the game ID into the URL is a nice way to do this.

@twoxfh made a couple of PRs with suggested changes to implement this, but has now closed them both.

https://github.com/diarmidmackenzie/blocks-arcade/pull/18
https://github.com/diarmidmackenzie/blocks-arcade/pull/19

Raising this issue to:
- track the desired feature
- create a space for discussion about the best implementation

@twoxfh - couple of questions for you:
- what did you think was wrong with your PRs 18 & 19?
- can you explain the rationale for this.  Specifically, thuis makes sense for me as a desirable feature for keyboard users (playing in a desktop browser).  But I'm not sure what you mean by "non-keyboard users" in your PR description?

**Comment by diarmidmackenzie** [comment]
Worth noting this other update I made which draws config from a URL.
https://github.com/diarmidmackenzie/blocks-arcade/commit/46276f163f4643197f04332b327ab3ef8b7762c7#diff-e4fd7f53a474fa4e8c0b4573ff0393c22c340545fceb9df9821872c17c04fad3

Perhaps there is a more elegant way to do this, but it seemed OK to me, and testing didn't show up any problems...

**Comment by diarmidmackenzie** [comment]
Final point - PR to add this function should ideally also include updates to README.md explaining the new params.

**Comment by twoxfh** [comment]
My first PR hardcoded the URL Param code in your scene-jumps component and index.html, which I thought wasn't good, My second PR made a start position attribute in your scene-jumps component, but then I wasn't sure how setFocus would be affected. I was reading up on Aframe and it turns out in the version you are using, you can call component member methods easily, so I used setPosition which means I did not have to worry about the above. I didn't make a PR with the latest code since I wanted it to marinate, and I included it in the warn-on-layer-settings component which I wasn't sure if that's what you wanted. It does work and its in my repo here: https://github.com/twoxfh/blocks-arcade/blob/main/pages/index.html. If this seems like a level headed approach, I will update the readme as well.

**Comment by diarmidmackenzie** [comment]
Hi - I don't particularly like the latest way you have done this.

The "warn-on-layer-settings" component has a specific function to make sure a warning pops up for people who are using layers configuration to display different views in each eye.

This is the wrong place to put this default scene jump function.

I don't actually see a problem with your first fix, where the URL parameter is accessed directly from the scene-jumps component.
https://github.com/diarmidmackenzie/blocks-arcade/pull/18/commits/487d322b4d3170f689cb754069a7d1e19e82a515

That seems like the right place to put this functionality.

I can see it's a bit of a pain that the HTML hard-codes the version of blocks-arcade-utils.js that's included.  That makes it harder than it should be to update blocks-arcade-utils.js, which may have been what caused you problems with the very first version of your fix.

The reason for pulling the JS from the jsdelivr CDN rather than the local directory is just to keep the load on the web server where I host this to a minimum.

Putting JS into the HTML is not a good solution to this, and the JS that I have included at the top of the HTML is bad practice and shouldn't really be there... it should be cleanly separated into a separate JS module.

My suggestion would be:
- re-open PR 18, and I'll merge that into the repo (together with a docs update if you can).
- I'll publish a new version of the utils file (0.5) including your changes, and update the HTML to refer to this version
- I'll open a separate issue to track the fact that having the block-arcade-utils.js version hardcoded in the HTML file is a bit of a problem for maintainability, and ponder how to improve that.  Not sure how much time/effort I'll put into this right now, since there's not a lot of active dev ongoing right now...

Many thanks for your interest, your PR, and your care in trying to find the right fix!

**Comment by twoxfh** [comment]
Thanks for your feedback. I got my repo back in order and created a pull request with documentation.

**Comment by diarmidmackenzie** [comment]
Thanks - I merged the PR, created a v0.4.1 release, and published at
https://blocksarcade.xyz/preview/index.html?start=3

Haven't had a chance to test in VR yet.  Want to do that before promoting this to the main URL, but should get a chance to do so later today.

**Comment by twoxfh** [comment]
Thamks. Works for me in my Vr. Did not try it with keyboard commands though. Did not have a problem using it with the other parameters either.

**Comment by diarmidmackenzie** [comment]
This is now live at https://blocksarcade.xyz/
